### ISSUE TITLE
Add Adaptive Pure Pursuit control

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#114]
I think we can improve the janky autonomous pathing with the help of pure pursuit.

I'll try to implement a controller

**Comment by wm-c** [comment]
This looks really neat, do you want me to work on any specific part?

**Comment by ewpratten** [comment]
I am working on my own code (and failing) Feel free to try for yourself. There is a fair amount of math

**Comment by ewpratten** [comment]
Added by #198
