### ISSUE TITLE
Figuring out which game stage the Robot is in. 

### ISSUE THREAD

**Issue by hyperliskdev** [frc5024/InfiniteRecharge#29]
## Goal

Create a new class (singleton) at `frc.robot.GameData` with methods for dealing with game state information.

It should expose the following methods:
```java
public GameStage getGameStage();
```

## Game Stage Enum

This enum should have the following:

 - Stage 1
 - Stage 2
 - Stage 3

## getGameStage method
Figure out which stage we are in:
- If we are in AUTO, return stage 1
- If in TeleOp and empty string is returned for FMS give stage 2
- If in TeleOP and returned string is not empty, stage 3

**Comment by ewpratten** [comment]
Here is the Javadoc for getting the GSM (Game Specific Message)

https://first.wpi.edu/FRC/roborio/release/docs/java//edu/wpi/first/wpilibj/DriverStation.html#getGameSpecificMessage()

**Comment by ewpratten** [comment]
Can you also add this method:

```java
public Color getControlColor();
```

This method should return `null` if the GSM string is empty, otherwise return a new `java.awt.color` object based on the string.

Following this conversion:

| GSM Data | Return value |
| -- | -- |
| "R" | `Color.RED` |
| "G" | `Color.GREEN` |
| "B" | `Color.BLUE` |
| "Y" | `Color.YELLOW` |


This page has info on how to read the FMS data:

https://docs.wpilib.org/en/latest/docs/software/wpilib-overview/2020-Game-Data.html


----

The `getGameStage` method should read this to determine if FMS has sent a color

**Comment by hyperliskdev** [comment]
This does assume that the 9 balls will be reached during the autonomous period as in the graph for Stage 1 it state: "Stage 1 has been activated when: nine (9) POWER CELLS are scored & TELEOP has begun"

**Comment by hyperliskdev** [comment]
Should the getControlColor method return the exact CMYB colors or does it matter at all?

**Comment by ewpratten** [comment]
Firstly, yes, we assume 9 balls have been sent

Second, returning the CMYB color is a great idea!

**Comment by ewpratten** [comment]
I noticed you checking `!driverstation.isAutonomous()` to see if we are in teleop. There is actually a method for this called [isOperatorControl()](https://first.wpi.edu/FRC/roborio/release/docs/java//edu/wpi/first/wpilibj/DriverStation.html#isOperatorControl())

**Comment by hyperliskdev** [comment]
Thanks! Will do the CMYB Colors, could be useful in driverstation/smart dashboard. Or not. Will change that to isOperatorControl().

**Comment by ewpratten** [comment]
Here is the table of color values from [3.5.1](https://firstfrc.blob.core.windows.net/frc2020/Manual/2020FRCGameSeasonManual.pdf#page=30):

| Control Panel Color | Cyan | Magenta | Yellow | Black |
| -- | -- | -- | -- | -- |
|Blue | 100|0|0|0|
|Green | 100|0|100|0|
|Red | 0|100|100|0|
|Yellow | 0|0|100|0|

**Comment by ewpratten** [comment]
@awpratten  was saying that we can actually use the color returned by `getControlColor` to compare to the current color sensor value to determine if we are looking at the right section or not

**Comment by ewpratten** [comment]
Can you add a class to `frc.lib5k.utils` called `ColorUtils`?

Inside, add a static public method called `epsilonEquals` that calls `MathUtils.epsilonEquals` on each of R G and B of two color objects, then returns if they are similar

```java
// ColorUtils

public static boolean epsilonEquals(Color a, Color b, double eps){
    return (MathUtils.epsilonEquals(a.r, b.r, eps) && MathUtils.epsilonEquals(a.g, b.g, eps) && MathUtils.epsilonEquals(a.b, b.b, eps));
}
```

```java
// frc.lib5k.utils.MathUtils

public static boolean epsilonEquals(double a, double b, double epsilon) {
    return (a - epsilon <= b) && (a + epsilon >= b);
}
```

**Comment by ewpratten** [comment]
we can then use that new method to determine if the color from the sensor is within a threshold of the desired one

**Comment by hyperliskdev** [comment]
Can we get the data from the sensor on the control panel? If not, we know which color is at a 90* angle to the correct color. 
![Capture](https://user-images.githubusercontent.com/32578619/71772875-305c4100-2f21-11ea-9198-5e1fa6b92c4f.PNG)

For example, yellow is perpendicular to green. If we are sensing yellow, we know it is in the green.

**Comment by hyperliskdev** [comment]
Will do on the ColorUtils.

**Comment by awpratten** [comment]
Colour not color. 🙄

**Comment by ewpratten** [comment]
Consistency is key ;)

**Comment by ewpratten** [comment]
We can not read the field sensor. We will need a lookup table of colors or something
