### ISSUE TITLE
Generate Gradle project

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#3]
On January 4th, we need to download the latest WPILib, RoboRIO image, and DriverStation. Then generate a new gradle project for the year. After this, we should drop in the latest Lib5K.

My laptop apparently has issues building gradle wrappers, so a windows user should do this to save us some headache. Ill handle Lib5K

**Comment by hyperliskdev** [comment]
Got it!

**Comment by ewpratten** [comment]
We should also add support for Idea, and eclipse

**Comment by ewpratten** [comment]
This was done by #13 I wasn't expecting an early WPILib release
