### ISSUE TITLE
Color Sensor V3 Testing and Calibration

### ISSUE THREAD

**Issue by hyperliskdev** [frc5024/InfiniteRecharge#33]
# Control Panel
On the control panel, there are 4 different colours that appear twice each. To detect which colour is currently under the Control Panel Sensor, we are using the Rev Robotics Color Sensor V3. 

## Color Sensor V3
This sensor returns 4 channel RGBA( ( 0-255 ), ( 0-255 ), ( 0,255 ), ( 0-255 ) )  and a proximity value ( 0- 10). 
The sensor also has an LED that can be toggled. It is a white LED that shines on the object/colour it is facing. Find out if this LED does any good or just makes things harder.

Get outputs from the sensor and use its data along with the colour comparison utility to detect which color is on the wheel.   

This is being worked on in color-sensor branch

**Comment by ewpratten** [comment]
Can you add a shuffleboard widget with a slider to adjust epsilon for color comparison?

**Comment by ewpratten** [comment]
Make a new shuffleboard tab called "Configuration" for the widget

**Comment by ewpratten** [comment]
Here is the docs for sending a number to shuffleboard:

https://docs.wpilib.org/en/latest/docs/software/wpilib-tools/shuffleboard/layouts-with-code/sending-data.html#sending-simple-data

There is a bit that calls `setDouble`, I think you can use `getDouble` instead to read the value.

**Comment by ewpratten** [comment]
Just thought about it. The threshold value should actually be stored on the robot, not the laptop.

Here is the API doc for doing this:

https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/Preferences.html

**Comment by ewpratten** [comment]
I am going to close this. Any updates on the sensor and its mech should be made into new issues
