### ISSUE TITLE
Add Trajectory following 

### ISSUE THREAD

**Issue by wm-c** [frc5024/InfiniteRecharge#35]
**Trajectory following needs to be added to the robot.**

This tutorial has the details on how to do this.

https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/trajectory-tutorial/index.html
Some data is required from the drive base before this project can be started

**Comment by ewpratten** [comment]
I have pulled this back to Week 1 because we need this done as soon as possible

**Comment by ewpratten** [comment]
@rsninja722 can you help out with this?

**Comment by ewpratten** [comment]
#39 will need to be completed before this

**Comment by rsninja722** [comment]
I tried to install the characterization tool, but pip gave me a terminal full of errors

**Comment by ewpratten** [comment]
This task is done. Just waiting on the fix for #65 to be merged, and the tuning in #69 and #63 to be merged after
