### ISSUE TITLE
Characterize MiniBot's drivetrain

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#39]
In order to complete #35, we need to run the `frc-characterization` tool on MiniBot. Can someone do this, follow the instructions in #35,  save all the values to `RobotConstants.java`, then make a PR for it?

**Comment by ewpratten** [comment]
@hyperliskdev do you think we can get this done today?

**Comment by hyperliskdev** [comment]
@Ewpratten if we access to mini-bot, definitely.

**Comment by ewpratten** [comment]
This is now in-progress. #48 added the project files for running telemetry and calculations
