### ISSUE TITLE
Pathweaver update is required

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#43]
[wpilibsuite/PathWeaver](https://github.com/wpilibsuite/PathWeaver) still has not been updated for 2020. We will have to generate trajectories manually (not a big deal, but it is nice to have a tool help us). 

@wm-c @rsninja722  Do you think [frc5024/PointPlanner](https://github.com/frc5024/PointPlanner) is ready for use to generate waypoints for now?

**Comment by rsninja722** [comment]
should be ready, just need the 2020 field image and the .json with the measurements

**Comment by wm-c** [comment]
I can see if I can get an image and the measurements from the manual.

**Comment by ewpratten** [comment]
ok

**Comment by wm-c** [comment]
I made a pull request to pathweaver to update it for 2020. Point Planner currently work with 2020, but it can't be run as a local file due to CORES access restriction. We will update it once the appropriate change to pathweavers happen.

**Comment by ewpratten** [comment]
This is being tracked in https://github.com/wpilibsuite/PathWeaver/pull/172

Thanks @wm-c  and @rsninja722  for making the PR!

**Comment by wm-c** [comment]
The Pathweaver pull request was merged into master
