### ISSUE TITLE
Flash Radio

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#7]
Comp bot's radio (router) must be updated to the latest firmware. 

## Flashing

A complete guide on flashing the radio can be found here: https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/radio-programming.html

## Settings

Make sure to use the following settings for the radio:

```
Team: 5024
WPA Key: raiderrobotics
Radio: OpenMesh
Mode: 2.4GHz Access Point
Robot Name: CarterIsChaotic
Firewall: <un-checked>
BW Limit: <checked>
```

**Comment by ewpratten** [comment]
Pushing this back to week 2.

@SRJacks  can you do this at lunch time or after school on Monday and Wednesday?

**Comment by ewpratten** [comment]
The radio names are:

| Robot Name | Radio name |
| -- | -- |
| MiniBot | DarianIsDaring |
| Competition bot | CarterIsChaotic |
| Router in the grey tote | (unknown for now) |

**Comment by hyperliskdev** [comment]
Finished as of January 23rd.

**Comment by ewpratten** [comment]
Requirements have been updated in description
