### ISSUE TITLE
Climb programming

### ISSUE THREAD

**Issue by slownie** [frc5024/InfiniteRecharge#70]
We need a climber on this robot.

Talk to build members and get all the specifications for said climber.

**Comment by slownie** [comment]
Bar isn't steel so no hall effect sensors, we will be able to use the limelight since its going to be mounted at the back of the robot

**Comment by slownie** [comment]
Use either an analog pressure sensor or an ultra sonic sensor

**Comment by ewpratten** [comment]
I think this will take a while to get mounted.. Will change the milestone if needed
