### ISSUE TITLE
Create Autonomous Path 

### ISSUE THREAD

**Issue by wm-c** [frc5024/InfiniteRecharge#72]
Create paths in for the autonomous to follow.

Use the following criteria to determine what the autonomous will do:

1. Scoring early (Y/N)
2. Picking up balls (Y/N)
   - Where? (Middle/ Lower)
3. Starting Position(Top/mid/Bot)
4. Get Out of the way?(Y/N)
   - Where?
5. Score Late(Y/N)

We will should also look into using shuffleboard to pass in augments.

**Comment by ewpratten** [comment]
Pushed back to week 2.
