### ISSUE TITLE
Update all CAN devices

### ISSUE THREAD

**Issue by ewpratten** [frc5024/InfiniteRecharge#8]
All of MiniBot's CAN devices will need a firmware update. Grab the latest firmware zip files for each device:

TalonSRX:
http://www.ctr-electronics.com/control-system/motor-control/talon-srx.html#product_tabs_technical_resources

PDP (**Only get this if the latest version is above 1.40**):
http://www.ctr-electronics.com/pdp.html#product_tabs_technical_resources

PCM (**Only get this if the latest version is above 1.65. Make sure to get the FRC version**):
http://www.ctr-electronics.com/pcm.html#product_tabs_technical_resources

## Flashing
Once all firmware files are downloaded, open up phoenix tuner (follow installation instructions in #6 ) , and go to the list of devices (while plugged in to the RIO). Update each device.

Follow this guide:
https://phoenix-documentation.readthedocs.io/en/latest/ch08_BringUpCAN.html#field-upgrade-devices

**Comment by ewpratten** [comment]
All CAN devices on MiniBot have been flashed.

We will have to flash the rest of the devices on the other two bots

**Comment by ewpratten** [comment]
Pushing back to week 2.

I need someone to update all TalonSRX devices on the comp bot prototype.. @hyperliskdev can you do it?

**Comment by hyperliskdev** [comment]
TalonSRX devices updated at lunch today.
