### ISSUE TITLE
Improving Colour Sensor and PanelManipulator.

### ISSUE THREAD

**Issue by hyperliskdev** [frc5024/InfiniteRecharge#91]
This issue is to keep track of progress of making the ColorSensorV3 do what we want it to do.
If anyone has ideas for things to add to the ColorSensor code or the PanelManipulator in general, talk about it here.

**Comment by hyperliskdev** [comment]
https://www.chiefdelphi.com/t/anyone-seeing-odd-results-from-rev-colorsensorv3/371871/5

- The RGB channels are overlapping
- getColor method is not mapping values correctly
- (255, 0, 0) and (100, 0, 0) have the same mapped values. (1.0, 0.0, 0.0)

**Comment by ewpratten** [comment]
Check out this video for an example of a panel controller that only uses color sensing:

https://youtu.be/sWrgcd2wdhc
